export default {
  HOME: "Home",
  Products: "products",
  ProductDetails: "productDetails",
  PROFILE: "profile",
  EDIT: "profileEdit",
  ACCOUNT: "Account",
  FAVOURITE: "favourite",
  LOGIN: "login",
  REGISTER: "register",
  JOINT: "join",
  CARTSEC: "shopBag",
  CART: "cart",
  CARTREVIEW: "cartReview",
  CARTDELIVERY: "delivery",
};
